# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "Snapshots")
    system("cp -r fastlane/screenshots/es-MX/ fastlane/screenshots/es-ES")
    upload_to_app_store(skip_binary_upload: true,
                        skip_metadata: true,
                        overwrite_screenshots: true,
                        run_precheck_before_submit: false)
  end
  
  lane :update_app_store do
    upload_to_app_store(skip_binary_upload: true,
                        skip_metadata: false,
                        overwrite_screenshots: true,
                        run_precheck_before_submit: false)
  end
end
