# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
 "iPad Pro (12.9-inch) (6th generation)",
 "iPhone 15 Pro Max",
 "iPhone SE (3rd generation)"
])

languages([
  "en-US",
  "es-MX",
  "fr-FR",
  "de-DE",
  "it",
  "ja",
  "ru",
  "zh-Hans",
  "zh-Hant"
])

# The name of the scheme which contains the UI Tests
scheme("Snapshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments(["reset_simulators"])

# For more information about all available options run
# fastlane action snapshot
