name: SwiftLint

on:
  push:
    paths:
      - '.github/workflows/lint-ios.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

defaults:
  run:
    working-directory: './iOS/ScoreTally'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: Source